# If root password is consistent, you can use it

- hosts: localhost
  connection: local

  tasks:
  - name: Generate SSH key for ansible
    user:
      name: root
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa_pgsql_ha

- hosts: pgsqlHA
  tasks:
  - name: Distribute authorized key for ansible
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '/root/.ssh/id_rsa_pgsql_ha.pub') }}"

